import { mkdirSync, readdirSync } from "node:fs";
import { readFile, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import type { FrameStore } from "./frameStore.js";

const FILENAME_RE = /^(\d{12})-(smooth|hard)\.png$/;

/**
 * Disk-backed FrameStore: PNGs live as <framesDir>/<timestamp>-smooth.png
 * and <framesDir>/<timestamp>-hard.png (one file per color-ramp variant -
 * see colorize.ts's `smooth` param). An in-memory Set of timestamps tracks
 * what's on disk without re-reading file bytes on every call; put/get only
 * touch disk for the actual PNGs. A timestamp is only indexed once BOTH
 * variant files are found for it, so an interrupted/partial write is
 * treated as missing and naturally regenerated by the poller's backfill
 * rather than causing a read failure later.
 *
 * All per-request I/O (get/put/evict) is async - this is the store behind
 * the hottest endpoint in the app (every scrub/poll/tab hits GET
 * /api/frames/:timestamp.png), so blocking the event loop on disk I/O here
 * would stall every other in-flight request. The startup directory scan
 * below is the one exception: it runs once, before the server starts
 * accepting requests, so there's nothing for a sync read to block.
 */
export function createDiskFrameStore(maxFrames: number, framesDir: string): FrameStore {
  mkdirSync(framesDir, { recursive: true });

  const variantsByTimestamp = new Map<string, Set<string>>();
  for (const name of readdirSync(framesDir)) {
    const match = FILENAME_RE.exec(name);
    if (!match) continue;
    const [, timestamp, variant] = match;
    if (!variantsByTimestamp.has(timestamp)) variantsByTimestamp.set(timestamp, new Set());
    variantsByTimestamp.get(timestamp)!.add(variant);
  }
  const index = new Set<string>(
    Array.from(variantsByTimestamp.entries())
      .filter(([, variants]) => variants.has("smooth") && variants.has("hard"))
      .map(([timestamp]) => timestamp),
  );

  function pathFor(timestamp: string, variant: "smooth" | "hard"): string {
    return path.join(framesDir, `${timestamp}-${variant}.png`);
  }

  async function evictExcess(): Promise<void> {
    const sorted = Array.from(index).sort();
    while (sorted.length > maxFrames) {
      const oldest = sorted.shift();
      if (oldest === undefined) break;
      index.delete(oldest);
      await Promise.all(
        (["smooth", "hard"] as const).map(async (variant) => {
          try {
            await unlink(pathFor(oldest, variant));
          } catch {
            // already gone; nothing to clean up
          }
        }),
      );
    }
  }

  // Fire-and-forget: only matters if maxFrames shrank since the last run (a
  // rare config change), not worth delaying server startup for.
  evictExcess().catch((err) => console.error("[frameStore] startup eviction failed:", err));

  async function get(timestamp: string, variant: "smooth" | "hard"): Promise<Buffer | undefined> {
    if (!index.has(timestamp)) return undefined;
    try {
      return await readFile(pathFor(timestamp, variant));
    } catch {
      index.delete(timestamp);
      return undefined;
    }
  }

  return {
    async put(frame) {
      await Promise.all([
        writeFile(pathFor(frame.timestamp, "smooth"), frame.pngSmooth),
        writeFile(pathFor(frame.timestamp, "hard"), frame.pngHard),
      ]);
      index.add(frame.timestamp);
      await evictExcess();
    },
    get,
    has(timestamp) {
      return index.has(timestamp);
    },
    list() {
      return Array.from(index)
        .sort()
        .map((timestamp) => ({ timestamp }));
    },
    async latest() {
      const sorted = Array.from(index).sort();
      const last = sorted[sorted.length - 1];
      if (last === undefined) return undefined;
      try {
        const [pngSmooth, pngHard] = await Promise.all([
          readFile(pathFor(last, "smooth")),
          readFile(pathFor(last, "hard")),
        ]);
        return { timestamp: last, pngSmooth, pngHard };
      } catch {
        index.delete(last);
        return undefined;
      }
    },
  };
}
