import { mkdirSync, readdirSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import path from "node:path";
import type { FrameStore } from "./frameStore.js";

const FILENAME_RE = /^(\d{12})-(smooth|hard)\.png$/;

/**
 * Disk-backed FrameStore: PNGs live as <framesDir>/<timestamp>-smooth.png
 * and <framesDir>/<timestamp>-hard.png (one file per color-ramp variant -
 * see colorize.ts's `smooth` param). An in-memory Set of timestamps tracks
 * what's on disk without re-reading file bytes on every call; put/get only
 * touch disk for the actual PNGs. A timestamp is only indexed once BOTH
 * variant files are found for it, so an interrupted/partial write is
 * treated as missing and naturally regenerated by the poller's backfill
 * rather than causing a read failure later.
 */
export function createDiskFrameStore(maxFrames: number, framesDir: string): FrameStore {
  mkdirSync(framesDir, { recursive: true });

  const variantsByTimestamp = new Map<string, Set<string>>();
  for (const name of readdirSync(framesDir)) {
    const match = FILENAME_RE.exec(name);
    if (!match) continue;
    const [, timestamp, variant] = match;
    if (!variantsByTimestamp.has(timestamp)) variantsByTimestamp.set(timestamp, new Set());
    variantsByTimestamp.get(timestamp)!.add(variant);
  }
  const index = new Set<string>(
    Array.from(variantsByTimestamp.entries())
      .filter(([, variants]) => variants.has("smooth") && variants.has("hard"))
      .map(([timestamp]) => timestamp),
  );

  function pathFor(timestamp: string, variant: "smooth" | "hard"): string {
    return path.join(framesDir, `${timestamp}-${variant}.png`);
  }

  function evictExcess(): void {
    const sorted = Array.from(index).sort();
    while (sorted.length > maxFrames) {
      const oldest = sorted.shift();
      if (oldest === undefined) break;
      index.delete(oldest);
      for (const variant of ["smooth", "hard"] as const) {
        try {
          unlinkSync(pathFor(oldest, variant));
        } catch {
          // already gone; nothing to clean up
        }
      }
    }
  }

  evictExcess();

  function get(timestamp: string) {
    if (!index.has(timestamp)) return undefined;
    try {
      return {
        timestamp,
        pngSmooth: readFileSync(pathFor(timestamp, "smooth")),
        pngHard: readFileSync(pathFor(timestamp, "hard")),
      };
    } catch {
      index.delete(timestamp);
      return undefined;
    }
  }

  return {
    put(frame) {
      writeFileSync(pathFor(frame.timestamp, "smooth"), frame.pngSmooth);
      writeFileSync(pathFor(frame.timestamp, "hard"), frame.pngHard);
      index.add(frame.timestamp);
      evictExcess();
    },
    get,
    has(timestamp) {
      return index.has(timestamp);
    },
    list() {
      return Array.from(index)
        .sort()
        .map((timestamp) => ({ timestamp }));
    },
    latest() {
      const sorted = Array.from(index).sort();
      const last = sorted[sorted.length - 1];
      return last ? get(last) : undefined;
    },
  };
}
